# Generated by Django 5.1.6 on 2025-03-12 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myhello", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="content",
            new_name="Course_Title",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="location",
            new_name="Department",
        ),
        migrations.RemoveField(
            model_name="post",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="post",
            name="title",
        ),
        migrations.AddField(
            model_name="post",
            name="Instructor",
            field=models.TextField(blank=True),
        ),
    ]
