# Generated by Django 5.1.6 on 2025-03-12 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myhello", "0002_rename_content_post_course_title_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="photo",
        ),
    ]
